# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VKUI2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 10, 741, 661))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 470, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(240, 470, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(20, 30, 681, 411))
        self.listWidget.setObjectName("listWidget")
        self.saveButton = QtWidgets.QPushButton(self.groupBox)
        self.saveButton.setGeometry(QtCore.QRect(20, 580, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.topLikesButton = QtWidgets.QPushButton(self.groupBox)
        self.topLikesButton.setGeometry(QtCore.QRect(510, 520, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.topLikesButton.setFont(font)
        self.topLikesButton.setObjectName("topLikesButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 570, 151, 51))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkJSON = QtWidgets.QRadioButton(self.groupBox_2)
        self.checkJSON.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.checkJSON.setChecked(True)
        self.checkJSON.setObjectName("checkJSON")
        self.checkExcel = QtWidgets.QRadioButton(self.groupBox_2)
        self.checkExcel.setGeometry(QtCore.QRect(80, 16, 82, 21))
        self.checkExcel.setObjectName("checkExcel")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(580, 560, 120, 80))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkLike = QtWidgets.QRadioButton(self.groupBox_3)
        self.checkLike.setGeometry(QtCore.QRect(10, 10, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkLike.setFont(font)
        self.checkLike.setChecked(True)
        self.checkLike.setObjectName("checkLike")
        self.checkRepost = QtWidgets.QRadioButton(self.groupBox_3)
        self.checkRepost.setGeometry(QtCore.QRect(10, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkRepost.setFont(font)
        self.checkRepost.setObjectName("checkRepost")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 520, 231, 41))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkUser = QtWidgets.QRadioButton(self.groupBox_4)
        self.checkUser.setGeometry(QtCore.QRect(20, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkUser.setFont(font)
        self.checkUser.setChecked(True)
        self.checkUser.setObjectName("checkUser")
        self.checkGroup = QtWidgets.QRadioButton(self.groupBox_4)
        self.checkGroup.setGeometry(QtCore.QRect(150, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkGroup.setFont(font)
        self.checkGroup.setObjectName("checkGroup")
        self.searchButton = QtWidgets.QPushButton(self.groupBox)
        self.searchButton.setGeometry(QtCore.QRect(340, 610, 91, 31))
        self.searchButton.setObjectName("searchButton")
        self.lineSearch = QtWidgets.QLineEdit(self.groupBox)
        self.lineSearch.setGeometry(QtCore.QRect(340, 570, 211, 31))
        self.lineSearch.setAlignment(QtCore.Qt.AlignCenter)
        self.lineSearch.setObjectName("lineSearch")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Количество постов на стене..."))
        self.pushButton.setText(_translate("MainWindow", "Получить записи"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "введите ссылку на группу или пользователя"))
        self.saveButton.setText(_translate("MainWindow", "сохранить данные"))
        self.topLikesButton.setText(_translate("MainWindow", "сначала популярные"))
        self.checkJSON.setText(_translate("MainWindow", "json"))
        self.checkExcel.setText(_translate("MainWindow", "excel"))
        self.checkLike.setText(_translate("MainWindow", "по лайкам"))
        self.checkRepost.setText(_translate("MainWindow", "по репостам"))
        self.checkUser.setText(_translate("MainWindow", "пользователя"))
        self.checkGroup.setText(_translate("MainWindow", "группы"))
        self.searchButton.setText(_translate("MainWindow", "поиск"))
        self.lineSearch.setPlaceholderText(_translate("MainWindow", "поиск по записям"))

